// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBb44d8LH3PRU1eiO6JMnzJBj4XMPtNAM',
    appId: '1:510486573042:web:41610c845150557925856b',
    messagingSenderId: '510486573042',
    projectId: 'furniture-app-a7d00',
    authDomain: 'furniture-app-a7d00.firebaseapp.com',
    databaseURL: 'https://furniture-app-a7d00-default-rtdb.firebaseio.com',
    storageBucket: 'furniture-app-a7d00.firebasestorage.app',
    measurementId: 'G-8SBMHM3KMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGVc7sRtS4kmlVDjhcSOPkdGgqF0Hrsg0',
    appId: '1:510486573042:android:ca32f71f25cfcf2625856b',
    messagingSenderId: '510486573042',
    projectId: 'furniture-app-a7d00',
    databaseURL: 'https://furniture-app-a7d00-default-rtdb.firebaseio.com',
    storageBucket: 'furniture-app-a7d00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHRoPiIm5dybCL6czbYnJvPn1Hs6575gA',
    appId: '1:510486573042:ios:4ac6f9b6b23332b125856b',
    messagingSenderId: '510486573042',
    projectId: 'furniture-app-a7d00',
    databaseURL: 'https://furniture-app-a7d00-default-rtdb.firebaseio.com',
    storageBucket: 'furniture-app-a7d00.firebasestorage.app',
    iosBundleId: 'com.example.newFurnitureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHRoPiIm5dybCL6czbYnJvPn1Hs6575gA',
    appId: '1:510486573042:ios:4ac6f9b6b23332b125856b',
    messagingSenderId: '510486573042',
    projectId: 'furniture-app-a7d00',
    databaseURL: 'https://furniture-app-a7d00-default-rtdb.firebaseio.com',
    storageBucket: 'furniture-app-a7d00.firebasestorage.app',
    iosBundleId: 'com.example.newFurnitureApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBb44d8LH3PRU1eiO6JMnzJBj4XMPtNAM',
    appId: '1:510486573042:web:16351f97ba719c5325856b',
    messagingSenderId: '510486573042',
    projectId: 'furniture-app-a7d00',
    authDomain: 'furniture-app-a7d00.firebaseapp.com',
    databaseURL: 'https://furniture-app-a7d00-default-rtdb.firebaseio.com',
    storageBucket: 'furniture-app-a7d00.firebasestorage.app',
    measurementId: 'G-0H8B4SEE74',
  );
}
